### ISSUE TITLE
Non-interactive send command to pane

### ISSUE THREAD

**Issue by thedeeno** [mhinz/vim-tmuxify#15]
I'd like to make a hotkey to send a command to the current pane. I don't want to be prompted for this command nor do I want it to change the 'current run' command. Is this possible?

**Comment by dpo** [comment]
I was also trying to figure this out, but the command you give doesn't work for me. I'm trying to fire up the `ipython` interpreter in the pane opened with `<leader>mn`. Two things happen:

1. a new pane is created (instead of sending the command to the one I already created),
2. `TxSend` still prompts me for a command.

When I try to perform the operations manually, here's what happens:

1. `<leader>mn` creates a new pane
2. `:call tmuxify#pane_send('echo hello')<cr>` returns the error message `tmuxify: The associated pane was already closed! Run :TxCreate.`

But using `<leader>ms` instead of step 2 does prompt me for a command, and the command is indeed sent to the pane that was opened in step 1.

Any ideas?
