### ISSUE TITLE
Error detected for pane_send: E117: Unknown function: systemlist

### ISSUE THREAD

**Issue by LmtEdition** [mhinz/vim-tmuxify#18]
I just installed vim-tmuxify on vim 7.4 patch 1-52 on Ubuntu 14.04. However, when I run TxSend, I get an error saying the function 'systemlist' is unknown. I'm assuming 'systemlist' is a function in newer versions of vim. Is it possible to have support for older versions of vim?
![tmuxify-error](https://cloud.githubusercontent.com/assets/1936993/6262075/d71f1ef6-b7b0-11e4-974d-23e1e7ded0ef.png)

**Comment by jebaum** [comment]
Thanks for the detailed issue report!

`systemlist()` was introduced in patch 248, and a serious bug with it was fixed in patch 256, so if it's possible to update to that patch or later it'll solve your problem. Having said that, it is definitely possible to support using the older `system()` function if `systemlist()` isn't available, but I'm not sure when I'll have time to write that code. Could be in the next few days, or could be a few weeks.

**Comment by jebaum** [comment]
@LmtEdition should be fixed now, let me know if there are any problems
